language: node_js
node_js:
- 'node' # latest
- 'lts/*' # latest lts release
- '8'
- '4.2' # fallback.

# Run on new infrastructure
sudo: false

# Some newer nodejs modules need a c++ compiler
env:
  - CXX=g++-4.8

# Get heroku toolbelt
addons:
  apt:
    sources:
    - heroku
    - ubuntu-toolchain-r-test
    packages:
    - heroku-toolbelt
    - g++-4.8