#!/bin/sh

# Source localconfigurations
source .env # DONT COMMIT THIS FILE
export HUBOT_LOG_LEVEL="info"
export PATH="node_modules/.bin:node_modules/hubot/node_modules/.bin:$PATH"

exec node_modules/.bin/hubot "$@" --name Alonzo --adapter shell

